name: Build Electron Installers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Build frontend and backend
        run: npm run build

      - name: Install Electron dependencies
        run: npm ci
        working-directory: electron

      - name: Build Electron app (Linux)
        run: npx electron-builder --linux
        working-directory: electron

      - name: List build output (diagnostics)
        run: ls -al electron/dist_electron/ || echo "No dist_electron directory"

      - name: Upload Installers
        uses: actions/upload-artifact@v4
        with:
          name: linux-installers
          path: electron/dist_electron/*
