name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Node and npm versions
        run: |
          node --version
          npm --version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: electron

      - name: Build Electron app and output to log
        run: |
          set -o pipefail
          npm run build --if-present --loglevel verbose | tee build-output.log
        working-directory: electron

      - name: Show build log
        if: always()
        run: |
          echo "=== BUILD LOG ==="
          cat electron/build-output.log || echo "No build log found"

      - name: List electron directory after build
        run: |
          echo "=== electron directory tree ==="
          ls -alh electron
          echo "=== electron/dist_electron directory tree ==="
          ls -alh electron/dist_electron || echo "No dist_electron directory found"

      - name: Check build output contents
        run: |
          if [ -d electron/dist_electron ]; then
            echo "dist_electron exists, contents:"
            ls -lAh electron/dist_electron
          else
            echo "dist_electron does not exist."
            exit 1
          fi

      - name: Upload Electron build artifact (try v4)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: electron-app-${{ matrix.os }}
          path: electron/dist_electron/
        continue-on-error: true

      - name: Upload Electron build artifact fallback (v2)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: electron-app-${{ matrix.os }}-fallback
          path: electron/dist_electron/
        continue-on-error: true

      - name: Upload build log always
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-log-${{ matrix.os }}
          path: electron/build-output.log
        continue-on-error: true

      - name: Notify if artifact upload failed
        if: failure()
        run: |
          echo "::warning::Build completed, but artifact upload failed (likely GitHub Actions infrastructure issue)."
