name: Build Electron Installers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Desktop Installers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (root)
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Set up Electron dependencies and scripts
        run: bash setup-electron-deps.sh

      - name: Install dependencies (electron)
        run: npm install
        working-directory: electron

      - name: Build Electron App
        run: |
          if [ "${{ matrix.platform }}" = "win" ]; then
            node build-electron.js --win
          elif [ "${{ matrix.platform }}" = "mac" ]; then
            node build-electron.js --mac
          elif [ "${{ matrix.platform }}" = "linux" ]; then
            node build-electron.js --linux
          fi

      - name: List Output Files
        run: ls -al dist_electron || echo "No dist_electron directory found"

      - name: Upload Installers
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-installers
          path: dist_electron/*
        if: success()
