name: Artifact Action Diagnostic

on:
  push:
    branches:
      - main

jobs:
  artifact-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy file
        run: echo "artifact test" > test.txt

      - name: Upload test artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt

      - name: Upload test artifact fallback (v2)
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact-fallback
          path: test.txt
        continue-on-error: true
